<!DOCTYPE html>
<html>
<head>
<title><?php echo self::get_title() ?></title>
<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" href="../design/favicon.png" />
<link rel="stylesheet" type="text/css" href="style.css" />
</head>
<body>
<div id="wrap">

<?php while (Messages::hasMessages()): ?>
<div class="message"><?php echo Messages::popMessage(); ?></div>
<?php endwhile; ?>
<?php while (Messages::hasWarnings()): ?>
<div class="message warning"><?php echo Messages::popWarning(); ?></div>
<?php endwhile; ?>
<?php while (Messages::hasErrors()): ?>
<div class="message error"><?php echo Messages::popError(); ?></div>
<?php endwhile; ?>

<?php if (get_config('use_openid') && User::getUser() !== null): ?>
<div id="userbar">
<?php echo User::getName() ?>,
<a href="../logout.php">выйти</a>
</div>
<?php endif; ?>

<div id="wrap2">
<?php echo $content ?>
</div>

<div id="footer"><a href="https://bitbucket.org/Pozadi/myfin">myfin</a>
<?php echo VERSION?> / <a href="../">"большая" версия</a></div>
</div>
</body>
</html>
<!--

Time: <?php echo number_format(Util::whatTimer(), 10)?> seconds
Db time: <?php echo number_format(Db::getFullQueryTime(), 10)?> seconds
Memory: <?php echo memory_get_peak_usage() ?> bytes


<?php if(get_config('debug')): while (Messages::hasDebug()): ?>
<?php echo Messages::popDebug(); ?>


<?php endwhile; endif;?>

-->