<!-- Simple OpenID Selector -->
<link rel="stylesheet" href="js/openid-selector/css/openid.css" />
<script type="text/javascript" src="js/jquery-1.4.4.min.js"></script>
<script type="text/javascript" src="js/openid-selector/js/openid-jquery.js"></script>
<script type="text/javascript" src="js/openid-selector/js/openid-jquery-ru.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        openid.init('openid_identifier');
        //openid.setDemoMode(true); //Не сабмитить форму, только для тестирования клиентского javascript'а
    });
</script>
<!-- /Simple OpenID Selector -->

<!-- Simple OpenID Selector -->
<form action="" method="get" id="openid_form">
    <input type="hidden" name="action" value="verify" />

    <fieldset>
        <legend>Войти или создать новый аккаунт</legend>

        <div id="openid_choice">
            <p>Пожалуйста, выберите вашего аккаунт-провайдера:</p>
            <div id="openid_btns"></div>
        </div>

        <div id="openid_input_area">
            <input id="openid_identifier" name="openid_identifier" type="text" value="http://" />
            <input id="openid_submit" type="submit" value="Войти"/>
        </div>
        <noscript>
            <p>OpenID это сервис который позволяет вам входить в разные веб-сайты пользуясь одной учетной записью.
			Узнайте <a href="http://openid.net/what/">больше о OpenID</a> и <a href="http://openid.net/get/">как получить OpenID аккаунт</a>.</p>
        </noscript>
    </fieldset>
</form>
<!-- /Simple OpenID Selector -->